name: Pylint

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd "Del 2"
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        cd "Del 2"
        pylint main.py
        pylint robot
        pylint app
